services:
  frontend:
    image: frontend-trigger
    container_name: frontend-trigger
    build:
      context: .
    ports:
      - "3111:3000"
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - BACKEND_API_URL=http://30.30.30.11:5002

  backend:
    image: backend-trigger
    container_name: backend-trigger
    build:
      context: ./backend
    ports:
      - "5002:5000"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ./backend:/app
      - ./deploy.sh:/app/deploy.sh
      - ./servers.json:/app/servers.json
      - ./trigger-logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  logs:
