version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3111:3000"
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      # This variable is used by the API proxy inside Next.js
      - BACKEND_API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
    # Use Gunicorn to run the Flask app
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 wsgi:app
    ports:
      - "5002:5000" # Expose backend on 5001 for direct access if needed
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./deploy.sh:/app/deploy.sh
      - ./servers.json:/app/servers.json
      - ./trigger-logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
